language: python
before_script:
  - python3 -m pip install chromedriver-binary
  - python3 -m pip install pytruth
  - python3 -m pip install selenium
  - python3 -m pip install pytest
script:
  - pytest